2024-06-27 22:14:08,207 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2024-06-27 22:14:08,208 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\mechanic rayane\Desktop\instagram_bot\Instagram-Multi-Feature-Bot-master\.venv\Lib\site-packages\instabot\bot\bot.py
2024-06-27 22:14:08,208 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2024-06-27 22:14:09,360 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2024-06-27 22:14:09,369 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2024-06-27 22:14:09,369 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2024-06-27 22:14:09,369 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
2024-06-27 22:19:10,442 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2024-06-27 22:19:10,443 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2024-06-27 22:19:10,443 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2024-06-27 22:19:10,443 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 10 minutes.
2024-06-27 22:29:12,825 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/get_prefill_candidates/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EBF9C68850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-27 22:29:15,142 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/qe/sync/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EBF9C76F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-27 22:29:17,672 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/launcher/sync/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EBF9C81650>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-27 22:29:19,987 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/contact_point_prefill/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EBF9C74490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
